openapi: 3.0.0
info:
  title: sah
  description: s a h
  version: 0.1.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://us-central1-odp-01.cloudfunctions.net/api
- url: https://virtserver.swaggerhub.com/R8800/sah/v0
  description: SwaggerHub API Auto Mocking
tags:
- name: class
- name: lesson
- name: video
paths:
  /{classId}/lessons:
    get:
      tags:
      - lesson
      summary: List lessons
      description: jikanの配列を返す
      parameters:
      - name: classId
        in: path
        description: ID of class
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lesson'
  /videos:
    get:
      tags:
      - video
      summary: List videos
      description: Videoを返す
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Video'
components:
  schemas:
    Class:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
      description: クラス
    Lesson:
      required:
      - duration
      - id
      - title
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        start:
          type: string
          format: date-time
        duration:
          type: integer
      description: 時間割の時間相当の概念、期間は問わない
      x-examples:
        example-1:
          title: 自由研究
          description: なんでもOK
          start: 2020-05-01T00:00:00.000Z
          duration: 45
    Video:
      required:
      - duration
      - id
      - publishedAt
      - title
      - url
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        url:
          type: string
        duration:
          type: string
        publishedAt:
          type: string
          format: date-time
        thumbnails:
          type: string
      x-examples:
        example-1:
          title: 『チバテレの学習支援番組』小学４年生社会①（千葉市教育委員会）（2020.5.15放送）【チバテレ公式】
          description: |-
            「わたしたちが住む千葉県」

            小中学生向けの学習支援番組を制作、チバテレ第２チャンネルで放送した動画を公開します。
          url: https://www.youtube.com/watch?v=B3RL4BZkZpY
          duration: "951"
          publishedAt: 2020-05-14T01:00:00.000Z
          thumbnails:
            default:
              url: https://i.ytimg.com/vi/7lCDEYXw3mM/default.jpg
            medium:
              url: https://i.ytimg.com/vi/7lCDEYXw3mM/mqdefault.jpg
            high:
              url: https://i.ytimg.com/vi/7lCDEYXw3mM/hqdefault.jpg
        example-2:
          title: 便利って本当にいいこと？
          description: 楽で便利な世界にならないかと夢想するＱくん。そこにチッチが、便利ってそんなにいいことなの？と問いかける。次第に、不便の中にも幸せがあることを知っていく。
          url: https://www.nhk.or.jp/sougou/q/?das_id=D0005180283_00000
          duration: "900"
          publishedAt: 2020-04-23T00:00:00.000Z
          thumbnails:
            default:
              url: https://www.nhk.or.jp/das/image/D0005180/D0005180283_00000_S_001.jpg
